# Generated by Django 4.2.2 on 2023-06-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="signuptype",
            field=models.CharField(
                blank=True,
                choices=[("H.O", "House Owner"), ("T", "Tenants")],
                max_length=200,
                null=True,
            ),
        ),
    ]
