# Generated by Django 4.2.2 on 2023-06-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_signuptype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="signuptype",
            field=models.CharField(
                choices=[("H.O", "House Owner"), ("T", "Tenants")],
                default="H.O",
                max_length=200,
            ),
        ),
    ]
